### ISSUE TITLE
Failed to decompress file info_headhunter_tex.sc

### ISSUE THREAD

**Issue by Red1860** [AriusX7/sc-extract#11]
hey, I followed all instructions but I am getting this error in most sc files, Failed to decompress file, I was able to obtain some.
How can I fix it?

**Comment by AriusX7** [comment]
`sc_extract` doesn't support some tex files at the moment, primarily those found Hay Day. Some Clash of Clans files aren't supported yet either.

Could you please tell the name and version of the game whose files you're trying to extract?

**Comment by Rohan200220** [comment]
I was trying Clash of Clans Latest Version, v-13.369.23

**Comment by Rohan200220** [comment]
Hey! Any updates on this?

**Comment by AriusX7** [comment]
> Hey! Any updates on this?

I've identified the issue and have a pull request open with the fix (#12). However, my CI tests are failing on Windows and Linux and I haven't been able to fix them yet.

I think the code is correct but my CI builds are missing some dependencies. If you'd like to test, you can try to compile it from source from the `lzham` branch and then try using it. I have a feeling it _will_ work but I'm not certain.

**Comment by Rohan200220** [comment]
I don't know how to compile, sorry :P , do you have a precompiled version for macOS? I am running macOS Catalina 10.15.7

**Comment by AriusX7** [comment]
Ah, no worries. I do have a precompiled version for macOS. The archive attached below contains the binary. Please let me know if it works for you.
[sc_extract.zip](https://github.com/AriusX7/sc-extract/files/5742306/sc_extract.zip)

**Comment by Rohan200220** [comment]
I tried the above attached version, and it works! :) no single error!

**Comment by Rohan200220** [comment]
I was also trying some normal sc files, but I read that you need quickbms for that, do you know if there is any version for quickbms for macOS Catalina?

**Comment by AriusX7** [comment]
Glad to know it is working!

A macOS build for Quickbms is available [here](https://github.com/ryopei/quickbms-macos/releases/tag/v0.8.0). It works on macOS Catalina for me.

**Comment by Rohan200220** [comment]
I tried this version, I am getting permission denied error, so I tried to change the permission using the chmod command, but then it says bad cpu type.

**Comment by AriusX7** [comment]
I'm unsure why it does not work for you. I've been using that version on both macOS Catalina and Big Sur and it works perfectly.

I found [this](https://aluigi.altervista.org/papers/quickbms_macosx.zip) download link on the official QuickBMS website. It is advertised for El Capitan but works for me on Big Sur.

**Comment by Rohan200220** [comment]
Thanks, quickbms from the above link works! I got the sc file extracted from the command, but how to extract png from the file extracted from quickbms?
it gives a error something like ' Expected extracted png image'

**Comment by AriusX7** [comment]
You need to follow the following steps to cut the sprites. I'll be using `ui_tex.sc` as example. Suppose you are in `sc` directory and all these files are in this directory.

1. Extract images from the `ui_tex.sc` file (this is the `-tex` extraction)
2. Use QuickBMS on the `ui.sc` file

Then do one of these:

- Extracting images from the first step will extract images in a folder named `extracts` in the `out_dir` (if you specify one). Copy these from the `extracts` folder to the parent `sc` folder. Then simply use `sc_extract` on the `ui` file and it'll work.
- Specify `extracts` folder as png folder using the `--png` option. You command will look something like this: `sc_extract ui --png ./extracts`.

The images will be extracted in a folder named `ui_out` inside the `extracts` folder (the tool will create an extracts folder if it doesn't exist).

**Comment by Rohan200220** [comment]
Thanks a lot! it works :)

**Comment by Rohan200220** [comment]
Hey, so there are some files in the SC folder that don’t have a tex_sc file. Do you know how to decrypt those?

**Comment by AriusX7** [comment]
Unfortunately, I'm not sure about those files.
