### ISSUE TITLE
Not able to extract any file

### ISSUE THREAD

**Issue by LMeiraba** [AriusX7/sc-extract#15]
When I run the program with a path to any file `.csv.` or `.cs` or `_tex.sc` it says `←[1;32mExtraction finished!←[0m` and stops but the extracts folder is empty. By the why I have only tested this for clash of clans files.

**Comment by AriusX7** [comment]
Are you using the tool on Windows? Can you please share the version of the game you're trying to extract?

**Comment by TaraHeide** [comment]
Hi! I also tried to extract .cs files, but extracts folder is empty. Tested for brawl stars files

**Comment by AriusX7** [comment]
> Hi! I also tried to extract .cs files, but extracts folder is empty. Tested for brawl stars files

May I know which operating system do you use and which game (and version) are you trying to extract?

**Comment by TaraHeide** [comment]
> > Hi! I also tried to extract .cs files, but extracts folder is empty. Tested for brawl stars files
> 
> May I know which operating system do you use and which game (and version) are you trying to extract?

Windows 10, I tried with 2 version of Brawl Stars - 35.179 and 41.150

**Comment by AriusX7** [comment]
The `.csv` files present in Brawl Stars are not compressed. You do not need to extract them, you can use any CSV reader software (such as Excel) to open them directly.
