### ISSUE TITLE
Newbie here

### ISSUE THREAD

**Issue by dinkiwinki** [AriusX7/sc-extract#16]
Hi guys! I'm a data scientist on the process and I would like to extract custom data from Brawl Stars for a personal project. Sadly I dont fully understand your tool and I'd love it if you could tell me wether what i want to do is possible with it or not.

I intend to extract the following discreet data from every battle:
Battle result
Picks
Damage output
Damage taken
Kills
Deaths

As well as continuous data:
Health value throught game
Damage value throught game

Thanks in advance!

**Comment by AriusX7** [comment]
Unfortunately, it is not possible to extract the data you want with `sc_extract`. `sc_extract` can only extract static data already present in game files.
